# Generated by Django 4.1 on 2022-09-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('major', models.CharField(max_length=25)),
                ('enrollment_status', models.CharField(choices=[('IN', 'Inquiry'), ('EN', 'Enrolled'), ('DF', 'Deferred')], default='IN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('intended_start', models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer')], default='FA', max_length=2)),
                ('intended_major', models.CharField(choices=[('CSCI', 'Computer Science'), ('CHEM', 'Chemistry'), ('ENGI', 'Engineering'), ('BIOL', 'Biology'), ('PHYS', 'Physics'), ('MATH', 'Mathematics'), ('ITEC', 'Information Technology'), ('BMAN', 'Business Management'), ('FIAC', 'Finance and Accounting'), ('EDUC', 'Education'), ('KNPT', 'Kinesiology and Physical Therapy'), ('ESCI', 'Environmental Science'), ('FOLA', 'Foreign Languages'), ('DANC', 'Dance'), ('MUSI', 'Music'), ('PRAR', 'Performing Arts'), ('AGSC', 'Agricultural Sciences'), ('CUAR', 'Culinary Arts'), ('FIPH', 'Film and Photography'), ('FDNU', 'Food and Nutrition')], max_length=35)),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('AP', 'Applied'), ('PR', 'Processed'), ('AC', 'Accepted'), ('DP', 'Deposited'), ('DN', 'Denied'), ('WL', 'Waitlisted'), ('WI', 'Withdrawn')], max_length=2)),
                ('last_updated', models.DateField()),
                ('school_last_attended', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_apps.applicant')),
            ],
        ),
    ]
