# Generated by Django 4.1.1 on 2022-09-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_apps', '0005_alter_applicant_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='intended_start',
            field=models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer'), ('WI', 'Winter')], default='FA', max_length=2),
        ),
    ]
